# cert-manager helm chart configuration values
# This file contains additional configuration settings and parameters used for the cert-manager helm chart installation.
# https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml

containerSecurityContext: # security context for cert-manager
  readOnlyRootFilesystem: true # If a container does not need to write files, it should be run with a read-only filesystem. 
  allowPrivilegeEscalation: false # Controls whether a process can gain more privileges than its parent process.
  privileged: false # Running a container as privileged gives all capabilities to the container, and it also lifts all the limitations enforced by the device cgroup controller.

cainjector: # security context for cert-manager ca injector
  containerSecurityContext:
    readOnlyRootFilesystem: true # If a container does not need to write files, it should be run with a read-only filesystem. 
    allowPrivilegeEscalation: false # Controls whether a process can gain more privileges than its parent process.
    privileged: false # Running a container as privileged gives all capabilities to the container, and it also lifts all the limitations enforced by the device cgroup controller.

webhook: # security context for cert-manager webhook
  containerSecurityContext:
    readOnlyRootFilesystem: true # If a container does not need to write files, it should be run with a read-only filesystem. 
    allowPrivilegeEscalation: false # Controls whether a process can gain more privileges than its parent process.
    privileged: false # Running a container as privileged gives all capabilities to the container, and it also lifts all the limitations enforced by the device cgroup controller.