# Job(s) that import/seed sample data into the deployed solution
jobs:

- job: importsampledata
  displayName: 'Import Sample Data'
  steps:

    - checkout: self # checkout github repository

    - download: current # download pipeline artifacts

    - template: steps-parse-terraform-output.yaml # parse global configuration settings from terraform deployment output
      parameters:
        workingDirectory: '$(Pipeline.Workspace)/terraformOutputGlobalInfra'  # Global infra deploy output directory

    - task: PowerShell@2
      displayName: 'Import Sample Data'
      retryCountOnTaskFailure: 1
      inputs:
        targetType: inline
        script: |

          # import and parse stamp terraform deployment outputs
          $releaseUnitInfraDeployOutput = Get-ChildItem $(Pipeline.Workspace)/terraformOutputReleaseUnitInfra/*.json | Get-Content | ConvertFrom-JSON

          $apiKey = $releaseUnitInfraDeployOutput.api_key.value

          # Take the first stamp. We only need to upload the test data once as it will be automatically globally distributed
          # We cannot send it through Front Door at this point, since the new stamp might not be wired up yet in AFD
          $stamp = $releaseUnitInfraDeployOutput.stamp_properties.value[0]

          $url = "https://$($stamp.aks_cluster_ingress_fqdn)/catalogservice/api/1.0/CatalogItem"

          Write-Host "*** Using URL $url"

          $testData =  Get-Content -Path "src/app/sampledata.json" | ConvertFrom-JSON

          $header = @{
            "X-Azure-FDID" = "$(frontdoor_id_header)"
            "X-API-KEY" = "$apiKey"
          }

          Write-Host "*** Found $($testData.catalogItems.Count) catalog items to import"

          foreach($catalogItem in $testData.catalogItems)
          {
              Write-Host "*** Importing item $($catalogItem.name)"
              $itemJson = $catalogItem | ConvertTo-Json -Compress

              # Call the Create CatalogItem API
              Invoke-WebRequest -Method POST `
                                -Uri $url `
                                -Headers $header `
                                -ContentType "application/json" `
                                -Body $itemJson
          }

