apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-memory
  namespace: chaos-testing
spec:
  mode: fixed-percent
  value: '50'
  selector:
    namespaces:
      - workload
  stressors:
    memory:
      workers: 1